// ============================================================
// VOCAB MANIA — Single source of truth
// ============================================================

export const APP_NAME = "Vocab Mania";
export const APP_DESCRIPTION =
  "The smarter way to build vocabulary for SSC, CAT, and competitive exams.";

export const NAV_LINKS = [
  { label: "Features", href: "#features" },
  { label: "How It Works", href: "#how-it-works" },
  { label: "Pricing", href: "#pricing" },
] as const;

export const NAV_CTA = { label: "Get started", href: "/signup" };

export const HERO = {
  tag: "AI-Powered Vocabulary Learning",
  headline: "Master every word, ace every exam.",
  subhead:
    "Spaced repetition, AI mnemonics, and adaptive quizzes — built for SSC, CAT, and every competitive exam that tests your word power.",
  primaryCta: { label: "Start learning free", href: "/signup" },
  secondaryCta: { label: "See how it works", href: "#how-it-works" },
  info: "Free for the first 200 words. No credit card required.",
};

export const FEATURES = {
  tag: "Features",
  headline: "Everything you need to own every word",
  subhead:
    "Built from the ground up for how aspirants actually learn — not a generic flashcard app.",
  items: [
    {
      category: "Learning",
      title: "Spaced Repetition Engine",
      description:
        "A scientifically-tuned algorithm that surfaces words right before you forget them. Reviews are scheduled, not guessed.",
      icon: "schedule",
    },
    {
      category: "AI",
      title: "AI Mnemonics Generator",
      description:
        "Every word gets a memorable story, visual cue, or association — generated by AI and personalized to your learning style.",
      icon: "auto_awesome",
    },
    {
      category: "Practice",
      title: "Adaptive Quiz System",
      description:
        "Quizzes that get harder when you're strong and gentler when you're struggling. Every session moves the needle.",
      icon: "quiz",
    },
    {
      category: "Analytics",
      title: "Mastery Dashboard",
      description:
        "Track your progress with word-level mastery scores, streak data, and exam-readiness predictions.",
      icon: "analytics",
    },
    {
      category: "Exams",
      title: "PYQ-Aligned Word Lists",
      description:
        "Words are tagged by exam, frequency, and year — so you study what actually appears, not random lists.",
      icon: "school",
    },
    {
      category: "Social",
      title: "Leaderboards & Streaks",
      description:
        "Compete with fellow aspirants. Daily streaks, weekly challenges, and rank boards keep you accountable.",
      icon: "emoji_events",
    },
  ],
};

export const HOW_IT_WORKS = {
  tag: "How It Works",
  headline: "Three steps to word mastery",
  subhead:
    "No clutter, no complexity — just a clear path from unknown to mastered.",
  steps: [
    {
      number: "01",
      title: "Choose your exam",
      description:
        "Pick SSC CGL, CAT, GRE, or any competitive exam. We load the most relevant word lists instantly.",
    },
    {
      number: "02",
      title: "Learn with AI",
      description:
        "Each word comes with a mnemonic, usage examples, and etymology. Our AI adapts explanations to how you think.",
    },
    {
      number: "03",
      title: "Master through repetition",
      description:
        "The engine schedules revisions at the perfect interval. You review fewer words but remember more of them.",
    },
  ],
};

export const TESTIMONIAL = {
  quote:
    "I went from knowing 200 words to 800 in six weeks. The mnemonics are absurdly effective — I still remember 'ephemeral' because of the story it gave me.",
  author: "Priya Sharma",
  role: "SSC CGL 2025 — Rank 34",
};

export const STATS = [
  { label: "Words mastered", value: "12,400+", delta: "across all users" },
  { label: "Active learners", value: "8,200+", delta: "this month" },
  { label: "Avg. retention", value: "94%", delta: "after 30 days" },
  { label: "Exams covered", value: "24", delta: "and growing" },
];

export const CTA = {
  headline: "Start mastering vocabulary today",
  body: "Join 8,200+ aspirants building word power with spaced repetition, AI mnemonics, and adaptive quizzes.",
  primaryCta: { label: "Get started free", href: "/signup" },
  secondaryCta: { label: "View pricing", href: "#pricing" },
  info: "Free for the first 200 words.",
};

export const FOOTER = {
  tagline: "Built for aspirants who take vocabulary seriously.",
  columns: [
    {
      title: "Product",
      links: [
        { label: "Features", href: "#features" },
        { label: "Pricing", href: "#pricing" },
        { label: "Changelog", href: "#changelog" },
        { label: "Roadmap", href: "#roadmap" },
      ],
    },
    {
      title: "Resources",
      links: [
        { label: "Blog", href: "#blog" },
        { label: "Word of the Day", href: "#word-of-the-day" },
        { label: "API Docs", href: "#api" },
        { label: "Community", href: "#community" },
      ],
    },
    {
      title: "Company",
      links: [
        { label: "About", href: "#about" },
        { label: "Contact", href: "#contact" },
        { label: "Privacy", href: "#privacy" },
        { label: "Terms", href: "#terms" },
      ],
    },
  ],
  copyright: `© ${new Date().getFullYear()} Vocab Mania. All rights reserved.`,
};
