export interface Word {
  id: string;
  word: string;
  pronunciation: string;
  partOfSpeech: "noun" | "verb" | "adjective" | "adverb";
  meaning: string;
  hindiMeaning: string;
  example: string;
  synonyms: string[];
  antonyms: string[];
  frequency: 1 | 2 | 3 | 4 | 5;
  category: "emotions" | "actions" | "descriptions" | "academic" | "social" | "legal" | "economy" | "nature";
  difficulty: "easy" | "medium" | "hard";
  root: string;
  yearsAsked: number[];
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  description: string;
  wordCount: number;
}

export interface ExamList {
  id: string;
  name: string;
  description: string;
  wordCount: number;
  difficulty: "easy" | "medium" | "hard";
}

export const WORD_CATEGORIES: Category[] = [
  { id: "emotions", name: "Emotions", icon: "❤️", description: "Words related to feelings and emotional states", wordCount: 15 },
  { id: "actions", name: "Actions", icon: "⚡", description: "Words describing actions and movements", wordCount: 15 },
  { id: "descriptions", name: "Descriptions", icon: "🎨", description: "Adjectives and descriptive words", wordCount: 18 },
  { id: "academic", name: "Academic", icon: "📚", description: "Formal and scholarly vocabulary", wordCount: 15 },
  { id: "social", name: "Social", icon: "👥", description: "Words related to society and interactions", wordCount: 13 },
  { id: "legal", name: "Legal", icon: "⚖️", description: "Law and governance related terms", wordCount: 10 },
  { id: "economy", name: "Economy", icon: "💰", description: "Financial and economic terminology", wordCount: 8 },
  { id: "nature", name: "Nature", icon: "🌿", description: "Words related to environment and nature", wordCount: 6 },
];

export const EXAM_LISTS: ExamList[] = [
  { id: "ssc-cgl", name: "SSC CGL", description: "Combined Graduate Level Examination - Tier 1 & 2 vocabulary", wordCount: 60, difficulty: "medium" },
  { id: "ssc-chsl", name: "SSC CHSL", description: "Combined Higher Secondary Level - essential vocabulary", wordCount: 50, difficulty: "easy" },
  { id: "cat", name: "CAT", description: "Common Admission Test - MBA entrance vocabulary", wordCount: 45, difficulty: "hard" },
  { id: "gre", name: "GRE", description: "Graduate Record Examinations - advanced vocabulary", wordCount: 35, difficulty: "hard" },
  { id: "bank-po", name: "Bank PO", description: "Bank Probationary Officer - banking & finance vocabulary", wordCount: 40, difficulty: "medium" },
  { id: "upsc", name: "UPSC", description: "Civil Services Examination - comprehensive vocabulary", wordCount: 55, difficulty: "hard" },
];

export const WORD_DATABASE: Word[] = [
  {
    id: "w001",
    word: "abandon",
    pronunciation: "/əˈbændən/",
    partOfSpeech: "verb",
    meaning: "To leave completely and finally; to give up",
    hindiMeaning: "त्याग देना; छोड़ देना",
    example: "The government had to abandon the project due to lack of funds.",
    synonyms: ["desert", "forsake", "relinquish"],
    antonyms: ["keep", "retain", "maintain"],
    frequency: 1,
    yearsAsked: [2022, 2023, 2024],
    category: "actions",
    difficulty: "easy",
    root: "a- (away) + bandon (to control)"
  },
  {
    id: "w002",
    word: "achieve",
    pronunciation: "/əˈtʃiːv/",
    partOfSpeech: "verb",
    meaning: "To successfully reach a goal through effort",
    hindiMeaning: "प्राप्त करना; सफल होना",
    example: "She worked hard to achieve her goal of becoming an IAS officer.",
    synonyms: ["accomplish", "attain", "reach"],
    antonyms: ["fail", "lose", "abandon"],
    frequency: 1,
    yearsAsked: [2022, 2023, 2024],
    category: "actions",
    difficulty: "easy",
    root: "a- (to) + cheive (chief/head)"
  },
  {
    id: "w003",
    word: "benefit",
    pronunciation: "/ˈbenɪfɪt/",
    partOfSpeech: "noun",
    meaning: "An advantage or profit gained from something",
    hindiMeaning: "लाभ; फायदा",
    example: "Education provides long-term benefits to society.",
    synonyms: ["advantage", "gain", "profit"],
    antonyms: ["disadvantage", "drawback", "loss"],
    frequency: 1,
    yearsAsked: [2022, 2023, 2024],
    category: "economy",
    difficulty: "easy",
    root: "bene (good) + fac (to do)"
  },
  {
    id: "w004",
    word: "capacity",
    pronunciation: "/kəˈpæsɪti/",
    partOfSpeech: "noun",
    meaning: "The maximum amount that can be contained or produced",
    hindiMeaning: "क्षमता; धारण क्षमता",
    example: "The stadium has a capacity of 50,000 spectators.",
    synonyms: ["ability", "volume", "capability"],
    antonyms: ["inability", "incapacity"],
    frequency: 1,
    yearsAsked: [2022, 2023, 2024],
    category: "academic",
    difficulty: "easy",
    root: "cap (to take) + -acity (state)"
  },
  {
    id: "w005",
    word: "decline",
    pronunciation: "/dɪˈklaɪn/",
    partOfSpeech: "verb",
    meaning: "To decrease or become less; to refuse politely",
    hindiMeaning: "गिरावट; अस्वीकार करना",
    example: "The economy showed signs of decline in the last quarter.",
    synonyms: ["decrease", "diminish", "refuse"],
    antonyms: ["increase", "rise", "accept"],
    frequency: 1,
    yearsAsked: [2022, 2023, 2024],
    category: "economy",
    difficulty: "easy",
    root: "de (down) + clinare (to lean)"
  },
  {
    id: "w006",
    word: "efficient",
    pronunciation: "/ɪˈfɪʃənt/",
    partOfSpeech: "adjective",
    meaning: "Achieving maximum productivity with minimum waste",
    hindiMeaning: "कुशल; दक्ष",
    example: "The new system is more efficient than the old one.",
    synonyms: ["effective", "competent", "productive"],
    antonyms: ["inefficient", "wasteful", "incompetent"],
    frequency: 1,
    yearsAsked: [2022, 2023, 2024],
    category: "descriptions",
    difficulty: "easy",
    root: "efficere (to accomplish)"
  },
  {
    id: "w007",
    word: "genuine",
    pronunciation: "/ˈdʒenjuɪn/",
    partOfSpeech: "adjective",
    meaning: "Truly what something is said to be; authentic",
    hindiMeaning: "असली; वास्तविक",
    example: "The museum displays genuine artifacts from the Mughal era.",
    synonyms: ["authentic", "real", "original"],
    antonyms: ["fake", "counterfeit", "artificial"],
    frequency: 1,
    yearsAsked: [2022, 2023, 2024],
    category: "descriptions",
    difficulty: "easy",
    root: "genu (knee/birth)"
  },
  {
    id: "w008",
    word: "aberration",
    pronunciation: "/ˌæbəˈreɪʃən/",
    partOfSpeech: "noun",
    meaning: "A departure from what is normal or expected",
    hindiMeaning: "विचलन; भटकाव",
    example: "The sudden spike in prices was an aberration in the market.",
    synonyms: ["anomaly", "deviation", "irregularity"],
    antonyms: ["norm", "standard", "regularity"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "academic",
    difficulty: "medium",
    root: "ab- (away) + err (to wander)"
  },
  {
    id: "w009",
    word: "benevolent",
    pronunciation: "/bəˈnevələnt/",
    partOfSpeech: "adjective",
    meaning: "Well-meaning and kindly; generous",
    hindiMeaning: "दयालु; परोपकारी",
    example: "The benevolent donor funded the entire scholarship program.",
    synonyms: ["kind", "generous", "charitable"],
    antonyms: ["malevolent", "cruel", "hostile"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "bene (good) + vol (wish)"
  },
  {
    id: "w010",
    word: "candid",
    pronunciation: "/ˈkændɪd/",
    partOfSpeech: "adjective",
    meaning: "Truthful and straightforward; frank",
    hindiMeaning: "सीधा; ईमानदार",
    example: "The minister gave a candid interview about the policy failures.",
    synonyms: ["frank", "honest", "open"],
    antonyms: ["deceitful", "evasive", "secretive"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "social",
    difficulty: "medium",
    root: "candidus (white)"
  },
  {
    id: "w011",
    word: "deteriorate",
    pronunciation: "/dɪˈtɪəriəreɪt/",
    partOfSpeech: "verb",
    meaning: "To become progressively worse",
    hindiMeaning: "बिगड़ना; खराब होना",
    example: "The condition of the roads continues to deteriorate during monsoon.",
    synonyms: ["worsen", "decline", "degrade"],
    antonyms: ["improve", "enhance", "recover"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "actions",
    difficulty: "medium",
    root: "deterior (worse)"
  },
  {
    id: "w012",
    word: "ephemeral",
    pronunciation: "/ɪˈfemərəl/",
    partOfSpeech: "adjective",
    meaning: "Lasting for a very short time",
    hindiMeaning: "क्षणिक; अल्पकालिक",
    example: "Fame is often ephemeral and fades quickly.",
    synonyms: ["fleeting", "transient", "temporary"],
    antonyms: ["permanent", "enduring", "eternal"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "epi- (upon) + hemera (day)"
  },
  {
    id: "w013",
    word: "facilitate",
    pronunciation: "/fəˈsɪlɪteɪt/",
    partOfSpeech: "verb",
    meaning: "To make easier or help bring about",
    hindiMeaning: "सुगम बनाना; सहायता करना",
    example: "Technology facilitates faster communication across distances.",
    synonyms: ["enable", "assist", "promote"],
    antonyms: ["hinder", "obstruct", "impede"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "actions",
    difficulty: "medium",
    root: "facilis (easy)"
  },
  {
    id: "w014",
    word: "gregarious",
    pronunciation: "/ɡrɪˈɡeəriəs/",
    partOfSpeech: "adjective",
    meaning: "Fond of company; sociable",
    hindiMeaning: "सामाजिक; मिलनसार",
    example: "Her gregarious nature made her popular at gatherings.",
    synonyms: ["sociable", "outgoing", "friendly"],
    antonyms: ["introverted", "reclusive", "solitary"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "social",
    difficulty: "medium",
    root: "greg (flock/herd)"
  },
  {
    id: "w015",
    word: "mitigate",
    pronunciation: "/ˈmɪtɪɡeɪt/",
    partOfSpeech: "verb",
    meaning: "To make less severe or painful",
    hindiMeaning: "कम करना; शमन करना",
    example: "Steps were taken to mitigate the effects of drought.",
    synonyms: ["alleviate", "reduce", "lessen"],
    antonyms: ["aggravate", "worsen", "intensify"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "actions",
    difficulty: "medium",
    root: "mitigare (to soften)"
  },
  {
    id: "w016",
    word: "precarious",
    pronunciation: "/prɪˈkeəriəs/",
    partOfSpeech: "adjective",
    meaning: "Not secure; dangerously likely to fall or collapse",
    hindiMeaning: "अस्थिर; जोखिम भरा",
    example: "The company's financial position is precarious.",
    synonyms: ["unstable", "insecure", "risky"],
    antonyms: ["secure", "stable", "safe"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "precarius (obtained by prayer)"
  },
  {
    id: "w017",
    word: "resilient",
    pronunciation: "/rɪˈzɪliənt/",
    partOfSpeech: "adjective",
    meaning: "Able to recover quickly from difficulties",
    hindiMeaning: "लचीला; सहनशील",
    example: "Indian economy has shown resilient growth despite global slowdown.",
    synonyms: ["tough", "strong", "adaptable"],
    antonyms: ["fragile", "vulnerable", "weak"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "resilire (to jump back)"
  },
  {
    id: "w018",
    word: "substantiate",
    pronunciation: "/səbˈstænʃieɪt/",
    partOfSpeech: "verb",
    meaning: "To provide evidence to support a claim",
    hindiMeaning: "प्रमाणित करना; पुष्टि करना",
    example: "The police could not substantiate the allegations against him.",
    synonyms: ["verify", "confirm", "validate"],
    antonyms: ["refute", "disprove", "deny"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "legal",
    difficulty: "medium",
    root: "substantia (substance)"
  },
  {
    id: "w019",
    word: "ubiquitous",
    pronunciation: "/juːˈbɪkwɪtəs/",
    partOfSpeech: "adjective",
    meaning: "Present, appearing, or found everywhere",
    hindiMeaning: "सर्वव्यापी; हर जगह मौजूद",
    example: "Smartphones have become ubiquitous in modern society.",
    synonyms: ["omnipresent", "pervasive", "universal"],
    antonyms: ["rare", "scarce", "limited"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "hard",
    root: "ubique (everywhere)"
  },
  {
    id: "w020",
    word: "magnanimous",
    pronunciation: "/mæɡˈnænɪməs/",
    partOfSpeech: "adjective",
    meaning: "Very generous or forgiving, especially towards a rival",
    hindiMeaning: "महानुभाव; उदार",
    example: "The magnanimous victor offered peace to the defeated nation.",
    synonyms: ["generous", "noble", "charitable"],
    antonyms: ["petty", "vindictive", "selfish"],
    frequency: 4,
    yearsAsked: [2023],
    category: "emotions",
    difficulty: "hard",
    root: "magnus (great) + animus (mind)"
  },
  {
    id: "w021",
    word: "perfunctory",
    pronunciation: "/pəˈfʌŋktəri/",
    partOfSpeech: "adjective",
    meaning: "Carried out with minimal effort or thought",
    hindiMeaning: "औपचारिक; बेरुचि",
    example: "He gave a perfunctory nod without really listening.",
    synonyms: ["cursory", "superficial", "halfhearted"],
    antonyms: ["thorough", "careful", "meticulous"],
    frequency: 4,
    yearsAsked: [2023],
    category: "descriptions",
    difficulty: "hard",
    root: "per- (through) + fungi (to perform)"
  },
  {
    id: "w022",
    word: "sycophant",
    pronunciation: "/ˈsɪkəfænt/",
    partOfSpeech: "noun",
    meaning: "A person who acts obsequiously to gain advantage",
    hindiMeaning: "चापलूस; खुशामदखोर",
    example: "The king surrounded himself with sycophants who agreed with everything.",
    synonyms: ["flatterer", "toady", "yes-man"],
    antonyms: ["critic", "opponent", "rebel"],
    frequency: 4,
    yearsAsked: [2023],
    category: "social",
    difficulty: "hard",
    root: "syco- (fig) + phainein (to show)"
  },
  {
    id: "w023",
    word: "perspicacious",
    pronunciation: "/ˌpɜːspɪˈkeɪʃəs/",
    partOfSpeech: "adjective",
    meaning: "Having a ready insight into things; shrewd",
    hindiMeaning: "तेज बुद्धि; सूझबूझ वाला",
    example: "The perspicacious judge immediately saw through the false evidence.",
    synonyms: ["astute", "shrewd", "perceptive"],
    antonyms: ["obtuse", "dim-witted", "unperceptive"],
    frequency: 5,
    yearsAsked: [2024],
    category: "academic",
    difficulty: "hard",
    root: "per- (through) + spicere (to look)"
  },
  {
    id: "w024",
    word: "surreptitious",
    pronunciation: "/ˌsʌrəpˈtɪʃəs/",
    partOfSpeech: "adjective",
    meaning: "Kept secret, especially because it would not be approved",
    hindiMeaning: "गुप्त; छिपा हुआ",
    example: "She took a surreptitious glance at her phone during the meeting.",
    synonyms: ["secret", "covert", "clandestine"],
    antonyms: ["open", "overt", "public"],
    frequency: 4,
    yearsAsked: [2023],
    category: "descriptions",
    difficulty: "hard",
    root: "surripere (to steal)"
  },
  {
    id: "w025",
    word: "ambiguous",
    pronunciation: "/æmˈbɪɡjuəs/",
    partOfSpeech: "adjective",
    meaning: "Open to more than one interpretation; unclear",
    hindiMeaning: "अस्पष्ट; दो अर्थों वाला",
    example: "The politician gave an ambiguous answer to avoid controversy.",
    synonyms: ["vague", "unclear", "equivocal"],
    antonyms: ["clear", "unambiguous", "definite"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "academic",
    difficulty: "medium",
    root: "ambi (both) + agere (to drive)"
  },
  {
    id: "w026",
    word: "arduous",
    pronunciation: "/ˈɑːdjuəs/",
    partOfSpeech: "adjective",
    meaning: "Involving great effort; difficult and tiring",
    hindiMeaning: "कठिन; कष्टसाध्य",
    example: "The arduous journey through the mountains tested their endurance.",
    synonyms: ["difficult", "strenuous", "laborious"],
    antonyms: ["easy", "effortless", "simple"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "arduous (burning/hot)"
  },
  {
    id: "w027",
    word: "benign",
    pronunciation: "/bɪˈnaɪn/",
    partOfSpeech: "adjective",
    meaning: "Gentle; kindly; not harmful",
    hindiMeaning: "सौम्य; कोमल; हानिरहित",
    example: "The doctor confirmed that the tumour was benign.",
    synonyms: ["harmless", "gentle", "kind"],
    antonyms: ["malignant", "harmful", "hostile"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "bene (good)"
  },
  {
    id: "w028",
    word: "capricious",
    pronunciation: "/kəˈprɪʃəs/",
    partOfSpeech: "adjective",
    meaning: "Given to sudden changes of mood or behaviour",
    hindiMeaning: "मनमौजी; चंचल",
    example: "The capricious weather made planning the outdoor event difficult.",
    synonyms: ["fickle", "unpredictable", "volatile"],
    antonyms: ["steady", "constant", "determined"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "capra (goat)"
  },
  {
    id: "w029",
    word: "conundrum",
    pronunciation: "/kəˈnʌndrəm/",
    partOfSpeech: "noun",
    meaning: "A confusing and difficult problem or question",
    hindiMeaning: "पहेली; कठिन समस्या",
    example: "The ethical conundrum left the committee divided.",
    synonyms: ["puzzle", "enigma", "dilemma"],
    antonyms: ["solution", "answer", "clarity"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "academic",
    difficulty: "medium",
    root: "Latin quinundrum (five-notched)"
  },
  {
    id: "w030",
    word: "dearth",
    pronunciation: "/dɜːθ/",
    partOfSpeech: "noun",
    meaning: "A scarcity or lack of something",
    hindiMeaning: "अभाव; कमी",
    example: "There is a dearth of qualified teachers in rural areas.",
    synonyms: ["scarcity", "shortage", "lack"],
    antonyms: ["abundance", "plenty", "surplus"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "economy",
    difficulty: "medium",
    root: "deore (dear/expensive)"
  },
  {
    id: "w031",
    word: "eloquent",
    pronunciation: "/ˈeləkwənt/",
    partOfSpeech: "adjective",
    meaning: "Fluent or persuasive in speaking or writing",
    hindiMeaning: "वाक्पटु; प्रभावशाली",
    example: "The leader's eloquent speech inspired the crowd.",
    synonyms: ["articulate", "fluent", "persuasive"],
    antonyms: ["inarticulate", "tongue-tied", "ineloquent"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "social",
    difficulty: "medium",
    root: "eloqui (to speak out)"
  },
  {
    id: "w032",
    word: "fortuitous",
    pronunciation: "/fɔːˈtjuːɪtəs/",
    partOfSpeech: "adjective",
    meaning: "Happening by accident or chance rather than design",
    hindiMeaning: "संयोगवश; आकस्मिक",
    example: "A fortuitous meeting at the airport led to a business partnership.",
    synonyms: ["accidental", "chance", "unexpected"],
    antonyms: ["planned", "deliberate", "intentional"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "fortuitus (by chance)"
  },
  {
    id: "w033",
    word: "gauche",
    pronunciation: "/ɡəʊʃ/",
    partOfSpeech: "adjective",
    meaning: "Lacking ease or grace; unsophisticated",
    hindiMeaning: "असभ्य; अकुशल",
    example: "His gauche behaviour at the formal dinner embarrassed everyone.",
    synonyms: ["awkward", "clumsy", "tactless"],
    antonyms: ["graceful", "elegant", "sophisticated"],
    frequency: 4,
    yearsAsked: [2023],
    category: "social",
    difficulty: "hard",
    root: "gauche (left/clumsy)"
  },
  {
    id: "w034",
    word: "hapless",
    pronunciation: "/ˈhæpləs/",
    partOfSpeech: "adjective",
    meaning: "Unfortunate; having no luck",
    hindiMeaning: "बेचारा; दुर्भाग्यशाली",
    example: "The hapless victims lost everything in the flood.",
    synonyms: ["unlucky", "unfortunate", "luckless"],
    antonyms: ["lucky", "fortunate", "blessed"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "hap (luck/luck) + -less"
  },
  {
    id: "w035",
    word: "iconoclast",
    pronunciation: "/aɪˈkɒnəklæst/",
    partOfSpeech: "noun",
    meaning: "A person who attacks cherished beliefs or institutions",
    hindiMeaning: "परम्परा भंजक; मूर्तिभंजक",
    example: "The iconoclast challenged traditional views on education.",
    synonyms: ["rebel", "nonconformist", "dissenter"],
    antonyms: ["conformist", "traditionalist", "supporter"],
    frequency: 4,
    yearsAsked: [2023],
    category: "social",
    difficulty: "hard",
    root: "eikon (image) + klastes (breaker)"
  },
  {
    id: "w036",
    word: "juxtapose",
    pronunciation: "/ˌdʒʌkstəˈpəʊz/",
    partOfSpeech: "verb",
    meaning: "To place side by side for comparison",
    hindiMeaning: "तुलना के लिए रखना; साथ रखना",
    example: "The exhibition juxtaposes ancient and modern art forms.",
    synonyms: ["compare", "contrast", "place together"],
    antonyms: ["separate", "isolate", "distance"],
    frequency: 4,
    yearsAsked: [2023],
    category: "academic",
    difficulty: "hard",
    root: "juxta (near) + pos (to place)"
  },
  {
    id: "w037",
    word: "laconic",
    pronunciation: "/ləˈkɒnɪk/",
    partOfSpeech: "adjective",
    meaning: "Using very few words; concise",
    hindiMeaning: "संक्षिप्त; अल्पवचन",
    example: "His laconic reply left everyone wondering what he meant.",
    synonyms: ["brief", "terse", "concise"],
    antonyms: ["verbose", "wordy", "long-winded"],
    frequency: 4,
    yearsAsked: [2023],
    category: "descriptions",
    difficulty: "hard",
    root: "Laconia (Sparta)"
  },
  {
    id: "w038",
    word: "mercurial",
    pronunciation: "/mɜːˈkjʊəriəl/",
    partOfSpeech: "adjective",
    meaning: "Subject to sudden changes of mood; volatile",
    hindiMeaning: "अस्थिर; बदलता रहने वाला",
    example: "Her mercurial temperament made her difficult to work with.",
    synonyms: ["volatile", "unpredictable", "changeable"],
    antonyms: ["stable", "consistent", "steady"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "Mercury (Roman god)"
  },
  {
    id: "w039",
    word: "nonchalant",
    pronunciation: "/ˈnɒnʃələnt/",
    partOfSpeech: "adjective",
    meaning: "Feeling calm and relaxed; not worried",
    hindiMeaning: "बेफिक्र; उदासीन",
    example: "He remained nonchalant despite the mounting pressure.",
    synonyms: ["casual", "unconcerned", "indifferent"],
    antonyms: ["anxious", "worried", "concerned"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "non (not) + chaloir (to feel)"
  },
  {
    id: "w040",
    word: "ostentatious",
    pronunciation: "/ˌɒstenˈteɪʃəs/",
    partOfSpeech: "adjective",
    meaning: "Characterized by vulgar or pretentious display",
    hindiMeaning: "दिखावटी; भव्य",
    example: "His ostentatious lifestyle attracted criticism from colleagues.",
    synonyms: ["showy", "pretentious", "flashy"],
    antonyms: ["modest", "understated", "simple"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "ostentare (to display)"
  },
  {
    id: "w041",
    word: "paradox",
    pronunciation: "/ˈpærədɒks/",
    partOfSpeech: "noun",
    meaning: "A seemingly contradictory statement that may be true",
    hindiMeaning: "विरोधाभास; विसंगति",
    example: "It is a paradox that work can both tire and energize us.",
    synonyms: ["contradiction", "anomaly", "puzzle"],
    antonyms: ["certainty", "consistency", "clarity"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "academic",
    difficulty: "medium",
    root: "para (beside) + doxa (opinion)"
  },
  {
    id: "w042",
    word: "quintessential",
    pronunciation: "/ˌkwɪntɪˈsenʃəl/",
    partOfSpeech: "adjective",
    meaning: "Representing the most perfect example of a quality",
    hindiMeaning: "सर्वोत्तम; मूर्त रूप",
    example: "Chai is the quintessential Indian beverage.",
    synonyms: ["typical", "ultimate", "classic"],
    antonyms: ["atypical", "uncharacteristic", "abnormal"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "hard",
    root: "quinta essentia (fifth element)"
  },
  {
    id: "w043",
    word: "relinquish",
    pronunciation: "/rɪˈlɪŋkwɪʃ/",
    partOfSpeech: "verb",
    meaning: "To voluntarily give up something held",
    hindiMeaning: "त्याग देना; छोड़ देना",
    example: "He was forced to relinquish his claim to the property.",
    synonyms: ["surrender", "abandon", "give up"],
    antonyms: ["retain", "keep", "hold"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "actions",
    difficulty: "medium",
    root: "relinquere (to leave behind)"
  },
  {
    id: "w044",
    word: "scrutinize",
    pronunciation: "/ˈskruːtənaɪz/",
    partOfSpeech: "verb",
    meaning: "To examine or inspect closely and thoroughly",
    hindiMeaning: "बारीकी से जांचना; परखना",
    example: "The auditor scrutinized every financial transaction.",
    synonyms: ["examine", "inspect", "analyze"],
    antonyms: ["overlook", "ignore", "skim"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "actions",
    difficulty: "medium",
    root: "scruta (rubbings/searchings)"
  },
  {
    id: "w045",
    word: "tenacious",
    pronunciation: "/tɪˈneɪʃəs/",
    partOfSpeech: "adjective",
    meaning: "Tending to keep a firm hold; persistent",
    hindiMeaning: "दृढ़; परिश्रमी",
    example: "Her tenacious effort led to success in the examination.",
    synonyms: ["persistent", "determined", "resolute"],
    antonyms: ["yielding", "weak", "indecisive"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "tenere (to hold)"
  },
  {
    id: "w046",
    word: "verbose",
    pronunciation: "/vɜːˈbəʊs/",
    partOfSpeech: "adjective",
    meaning: "Using more words than needed; wordy",
    hindiMeaning: "वाचाल; शब्दबहुल",
    example: "His verbose explanation confused rather than clarified.",
    synonyms: ["wordy", "long-winded", "prolix"],
    antonyms: ["concise", "brief", "terse"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "verbum (word)"
  },
  {
    id: "w047",
    word: "watershed",
    pronunciation: "/ˈwɔːtəʃed/",
    partOfSpeech: "noun",
    meaning: "An event marking a turning point",
    hindiMeaning: "निर्णाण मोड़; विभाजित रेखा",
    example: "The 1991 economic reforms were a watershed moment for India.",
    synonyms: ["turning point", "milestone", "landmark"],
    antonyms: ["triviality", "insignificance"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "nature",
    difficulty: "medium",
    root: "water + shed (divide)"
  },
  {
    id: "w048",
    word: "zealous",
    pronunciation: "/ˈzeləs/",
    partOfSpeech: "adjective",
    meaning: "Having great energy or enthusiasm for a cause",
    hindiMeaning: "उत्साही; जोशपूर्ण",
    example: "The zealous volunteers worked through the night to help flood victims.",
    synonyms: ["enthusiastic", "passionate", "fervent"],
    antonyms: ["apathetic", "indifferent", "lethargic"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "zelos (zeal)"
  },
  {
    id: "w049",
    word: "acumen",
    pronunciation: "/ˈækjʊmən/",
    partOfSpeech: "noun",
    meaning: "The ability to make good judgments and quick decisions",
    hindiMeaning: "तीक्ष्ण बुद्धि; सूझबूझ",
    example: "Her business acumen helped her build a successful company.",
    synonyms: ["shrewdness", "insight", "astuteness"],
    antonyms: ["ignorance", "stupidity", "ineptitude"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "academic",
    difficulty: "medium",
    root: "acuere (to sharpen)"
  },
  {
    id: "w050",
    word: "bellicose",
    pronunciation: "/ˈbelɪkəʊs/",
    partOfSpeech: "adjective",
    meaning: "Demonstrating aggression and willingness to fight",
    hindiMeaning: "युद्धकारी; आक्रामक",
    example: "The bellicose rhetoric escalated tensions between the two nations.",
    synonyms: ["aggressive", "combative", "hostile"],
    antonyms: ["peaceful", "pacifist", "conciliatory"],
    frequency: 4,
    yearsAsked: [2023],
    category: "social",
    difficulty: "hard",
    root: "bellum (war)"
  },
  {
    id: "w051",
    word: "circumvent",
    pronunciation: "/ˌsɜːkəmˈvent/",
    partOfSpeech: "verb",
    meaning: "To find a way around an obstacle or rule",
    hindiMeaning: "बचना; टाल देना",
    example: "They tried to circumvent the new regulations through legal loopholes.",
    synonyms: ["bypass", "evade", "avoid"],
    antonyms: ["confront", "face", "obey"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "actions",
    difficulty: "medium",
    root: "circum (around) + venire (to come)"
  },
  {
    id: "w052",
    word: "duplicity",
    pronunciation: "/djuːˈplɪsɪti/",
    partOfSpeech: "noun",
    meaning: "Deceitfulness; double-dealing",
    hindiMeaning: "दोहरापन; छल",
    example: "His duplicity was revealed when the letters were published.",
    synonyms: ["deceit", "deception", "dishonesty"],
    antonyms: ["honesty", "sincerity", "candour"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "social",
    difficulty: "medium",
    root: "duplicitas (double)"
  },
  {
    id: "w053",
    word: "emancipate",
    pronunciation: "/ɪˈmænsɪpeɪt/",
    partOfSpeech: "verb",
    meaning: "To set free from legal or social restrictions",
    hindiMeaning: "मुक्त करना; आज़ाद करना",
    example: "The movement sought to emancipate women from social oppression.",
    synonyms: ["liberate", "free", "release"],
    antonyms: ["enslave", "imprison", "confine"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "legal",
    difficulty: "medium",
    root: "e- (out) + mancipium (ownership)"
  },
  {
    id: "w054",
    word: "frugal",
    pronunciation: "/ˈfruːɡəl/",
    partOfSpeech: "adjective",
    meaning: "Sparing or economical with regard to money or food",
    hindiMeaning: "मितव्ययी; संतोषी",
    example: "Despite his wealth, he lived a frugal lifestyle.",
    synonyms: ["thrifty", "economical", "prudent"],
    antonyms: ["extravagant", "wasteful", "lavish"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "economy",
    difficulty: "medium",
    root: "frugalis (fruitful/thrifty)"
  },
  {
    id: "w055",
    word: "gregarious",
    pronunciation: "/ɡrɪˈɡeəriəs/",
    partOfSpeech: "adjective",
    meaning: "Fond of company; sociable",
    hindiMeaning: "सामाजिक; मिलनसार",
    example: "Her gregarious nature made her popular at gatherings.",
    synonyms: ["sociable", "outgoing", "friendly"],
    antonyms: ["introverted", "reclusive", "solitary"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "social",
    difficulty: "medium",
    root: "greg (flock/herd)"
  },
  {
    id: "w056",
    word: "hypothesis",
    pronunciation: "/haɪˈpɒθəsɪs/",
    partOfSpeech: "noun",
    meaning: "A proposed explanation made on limited evidence",
    hindiMeaning: "परिकल्पना; अनुमान",
    example: "The scientist tested her hypothesis through rigorous experiments.",
    synonyms: ["theory", "assumption", "proposition"],
    antonyms: ["fact", "certainty", "proof"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "academic",
    difficulty: "medium",
    root: "hypo (under) + thesis (placing)"
  },
  {
    id: "w057",
    word: "impervious",
    pronunciation: "/ɪmˈpɜːviəs/",
    partOfSpeech: "adjective",
    meaning: "Not allowing fluid to pass through; unable to be affected",
    hindiMeaning: "अभेद्य; प्रभावहीन",
    example: "He seemed impervious to criticism from his peers.",
    synonyms: ["immune", "resistant", "impenetrable"],
    antonyms: ["susceptible", "vulnerable", "permeable"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "im- (not) + pervius (passable)"
  },
  {
    id: "w058",
    word: "juxtaposition",
    pronunciation: "/ˌdʒʌkstəpəˈzɪʃən/",
    partOfSpeech: "noun",
    meaning: "The fact of placing things close together for contrast",
    hindiMeaning: "सन्निकट स्थिति; तुलनात्मक स्थिति",
    example: "The juxtaposition of wealth and poverty shocked the visitors.",
    synonyms: ["comparison", "contrast", "adjacency"],
    antonyms: ["separation", "distance"],
    frequency: 4,
    yearsAsked: [2023],
    category: "academic",
    difficulty: "hard",
    root: "juxta (near) + positio (placing)"
  },
  {
    id: "w059",
    word: "kowtow",
    pronunciation: "/ˌkaʊˈtaʊ/",
    partOfSpeech: "verb",
    meaning: "To act in an excessively submissive manner",
    hindiMeaning: "चापलूसी करना; झुकना",
    example: "Employees should not kowtow to unreasonable demands.",
    synonyms: ["submit", "bow", "yield"],
    antonyms: ["defy", "resist", "rebel"],
    frequency: 4,
    yearsAsked: [2023],
    category: "social",
    difficulty: "hard",
    root: "Chinese koutou (knock head)"
  },
  {
    id: "w060",
    word: "litigious",
    pronunciation: "/lɪˈtɪdʒəs/",
    partOfSpeech: "adjective",
    meaning: "Concerned with lawsuits; tending to argue",
    hindiMeaning: "विवादप्रिय; मुकदमेबाज",
    example: "The litigious nature of the company led to many court cases.",
    synonyms: ["quarrelsome", "combative", "contentious"],
    antonyms: ["amicable", "peaceful", "non-litigious"],
    frequency: 4,
    yearsAsked: [2023],
    category: "legal",
    difficulty: "hard",
    root: "litigium (lawsuit)"
  },
  {
    id: "w061",
    word: "mundane",
    pronunciation: "/mʌnˈdeɪn/",
    partOfSpeech: "adjective",
    meaning: "Lacking interest or excitement; dull",
    hindiMeaning: "साधारण; रोज़मर्रा का",
    example: "She wanted to escape her mundane routine and travel the world.",
    synonyms: ["ordinary", "dull", "banal"],
    antonyms: ["exciting", "extraordinary", "fascinating"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "easy",
    root: "mundanus (worldly)"
  },
  {
    id: "w062",
    word: "nefarious",
    pronunciation: "/nɪˈfeəriəs/",
    partOfSpeech: "adjective",
    meaning: "Wicked or criminal in nature",
    hindiMeaning: "दुराचारी; अनैतिक",
    example: "The police exposed the nefarious activities of the crime syndicate.",
    synonyms: ["wicked", "evil", "villainous"],
    antonyms: ["virtuous", "righteous", "noble"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "legal",
    difficulty: "medium",
    root: "nefas (crime)"
  },
  {
    id: "w063",
    word: "obfuscate",
    pronunciation: "/ˈɒbfʌskeɪt/",
    partOfSpeech: "verb",
    meaning: "To make unclear or unintelligible",
    hindiMeaning: "अस्पष्ट करना; धुंधला करना",
    example: "The official tried to obfuscate the truth with complex language.",
    synonyms: ["confuse", "obscure", "muddle"],
    antonyms: ["clarify", "explain", "illuminate"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "actions",
    difficulty: "medium",
    root: "ob- (over) + fuscus (dark)"
  },
  {
    id: "w064",
    word: "placate",
    pronunciation: "/pləˈkeɪt/",
    partOfSpeech: "verb",
    meaning: "To make someone less angry or hostile",
    hindiMeaning: "शांत करना; तुष्ट करना",
    example: "The company offered refunds to placate angry customers.",
    synonyms: ["appease", "calm", "pacify"],
    antonyms: ["provoke", "anger", "irritate"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "actions",
    difficulty: "medium",
    root: "placare (to soothe)"
  },
  {
    id: "w065",
    word: "querulous",
    pronunciation: "/ˈkwerələs/",
    partOfSpeech: "adjective",
    meaning: "Complaining in a petulant or whining manner",
    hindiMeaning: "शिकायती; झगड़ालू",
    example: "The querulous patient complained about everything in the hospital.",
    synonyms: ["complaining", "whiny", "petulant"],
    antonyms: ["content", "agreeable", "cheerful"],
    frequency: 4,
    yearsAsked: [2023],
    category: "emotions",
    difficulty: "hard",
    root: "queri (to complain)"
  },
  {
    id: "w066",
    word: "reticent",
    pronunciation: "/ˈretɪsənt/",
    partOfSpeech: "adjective",
    meaning: "Not revealing one's thoughts or feelings readily",
    hindiMeaning: "गुप्त; मौन",
    example: "She was reticent about her plans for the future.",
    synonyms: ["reserved", "quiet", "taciturn"],
    antonyms: ["outgoing", "forthcoming", "communicative"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "reticere (to keep silent)"
  },
  {
    id: "w067",
    word: "sagacious",
    pronunciation: "/səˈɡeɪʃəs/",
    partOfSpeech: "adjective",
    meaning: "Having good judgment; wise",
    hindiMeaning: "बुद्धिमान; समझदार",
    example: "The sagacious leader anticipated the crisis before it happened.",
    synonyms: ["wise", "shrewd", "perceptive"],
    antonyms: ["foolish", "unwise", "ignorant"],
    frequency: 4,
    yearsAsked: [2023],
    category: "academic",
    difficulty: "hard",
    root: "sagax (wise)"
  },
  {
    id: "w068",
    word: "taciturn",
    pronunciation: "/ˈtæsɪtɜːn/",
    partOfSpeech: "adjective",
    meaning: "Reserved or uncommunicative in speech",
    hindiMeaning: "मौन; कम बोलने वाला",
    example: "The taciturn professor rarely spoke outside the classroom.",
    synonyms: ["silent", "reserved", "quiet"],
    antonyms: ["talkative", "loquacious", "chatty"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "social",
    difficulty: "medium",
    root: "tacitus (silent)"
  },
  {
    id: "w069",
    word: "vociferous",
    pronunciation: "/vəˈsɪfərəs/",
    partOfSpeech: "adjective",
    meaning: "Expressing feelings or opinions loudly and forcefully",
    hindiMeaning: "हो-हल्ला करने वाला; जोर से बोलने वाला",
    example: "The vociferous protests forced the government to reconsider.",
    synonyms: ["loud", "clamorous", "outspoken"],
    antonyms: ["quiet", "soft-spoken", "muted"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "social",
    difficulty: "medium",
    root: "vociferari (to cry out)"
  },
  {
    id: "w070",
    word: "whimsical",
    pronunciation: "/ˈwɪmzɪkəl/",
    partOfSpeech: "adjective",
    meaning: "Playfully quaint or fanciful; unpredictable",
    hindiMeaning: "चंचल; कल्पनाशील",
    example: "The whimsical design of the building delighted visitors.",
    synonyms: ["fanciful", "playful", "capricious"],
    antonyms: ["serious", "practical", "sober"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "whim (sudden fancy)"
  },
  {
    id: "w071",
    word: "austere",
    pronunciation: "/ɒˈstɪə/",
    partOfSpeech: "adjective",
    meaning: "Severe or strict in manner or appearance",
    hindiMeaning: "सख्त; संयमी",
    example: "The monk lived an austere life in the mountains.",
    synonyms: ["strict", "stern", "severe"],
    antonyms: ["luxurious", "indulgent", "lavish"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "austeros (harsh)"
  },
  {
    id: "w072",
    word: "brazen",
    pronunciation: "/ˈbreɪzən/",
    partOfSpeech: "adjective",
    meaning: "Bold and without shame",
    hindiMeaning: "निर्लज्ज; बेशर्म",
    example: "The brazen theft occurred in broad daylight.",
    synonyms: ["bold", "shameless", "audacious"],
    antonyms: ["modest", "shy", "timid"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "brasen (of brass)"
  },
  {
    id: "w073",
    word: "chronicle",
    pronunciation: "/ˈkrɒnɪkəl/",
    partOfSpeech: "noun",
    meaning: "A factual written account of important events",
    hindiMeaning: "इतिवृत्त; इतिहास",
    example: "The chronicle of the dynasty spans over three centuries.",
    synonyms: ["record", "history", "account"],
    antonyms: ["fiction", "myth", "legend"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "academic",
    difficulty: "medium",
    root: "chronos (time)"
  },
  {
    id: "w074",
    word: "dearth",
    pronunciation: "/dɜːθ/",
    partOfSpeech: "noun",
    meaning: "A scarcity or lack of something",
    hindiMeaning: "अभाव; कमी",
    example: "There is a dearth of skilled workers in the manufacturing sector.",
    synonyms: ["scarcity", "shortage", "lack"],
    antonyms: ["abundance", "plenty", "surplus"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "economy",
    difficulty: "medium",
    root: "deore (dear/expensive)"
  },
  {
    id: "w075",
    word: "ebullient",
    pronunciation: "/ɪˈbʌliənt/",
    partOfSpeech: "adjective",
    meaning: "Cheerful and full of energy",
    hindiMeaning: "उत्साही; जोशीला",
    example: "Her ebullient personality lit up the entire room.",
    synonyms: ["exuberant", "enthusiastic", "vivacious"],
    antonyms: ["subdued", "melancholy", "gloomy"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "ebullire (to boil over)"
  },
  {
    id: "w076",
    word: "fastidious",
    pronunciation: "/fæˈstɪdiəs/",
    partOfSpeech: "adjective",
    meaning: "Very attentive to accuracy and detail",
    hindiMeaning: "सूक्ष्म; सावधान",
    example: "The fastidious editor caught every grammatical error.",
    synonyms: ["meticulous", "particular", "fussy"],
    antonyms: ["careless", "sloppy", "casual"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "fastidium (dislike)"
  },
  {
    id: "w077",
    word: "grandiloquent",
    pronunciation: "/ɡrænˈdɪləkwənt/",
    partOfSpeech: "adjective",
    meaning: "Pompous or extravagant in language or style",
    hindiMeaning: "भव्य; भारी-भरकम",
    example: "His grandiloquent speech failed to impress the audience.",
    synonyms: ["pompous", "bombastic", "pretentious"],
    antonyms: ["modest", "understated", "plain"],
    frequency: 5,
    yearsAsked: [2024],
    category: "descriptions",
    difficulty: "hard",
    root: "grandis (great) + loqui (to speak)"
  },
  {
    id: "w078",
    word: "harangue",
    pronunciation: "/həˈræŋ/",
    partOfSpeech: "noun",
    meaning: "A lengthy and aggressive speech",
    hindiMeaning: "भाषण; फटकार",
    example: "The manager's harangue about punctuality left everyone uncomfortable.",
    synonyms: ["tirade", "diatribe", "lecture"],
    antonyms: ["whisper", "murmur"],
    frequency: 4,
    yearsAsked: [2023],
    category: "social",
    difficulty: "hard",
    root: "arang (arena)"
  },
  {
    id: "w079",
    word: "impugn",
    pronunciation: "/ɪmˈpjuːn/",
    partOfSpeech: "verb",
    meaning: "To dispute the truth or honesty of something",
    hindiMeaning: "विवाद करना; चुनौती देना",
    example: "The lawyer tried to impugn the witness's credibility.",
    synonyms: ["challenge", "question", "dispute"],
    antonyms: ["support", "defend", "validate"],
    frequency: 4,
    yearsAsked: [2023],
    category: "legal",
    difficulty: "hard",
    root: "impugnare (to attack)"
  },
  {
    id: "w080",
    word: "lugubrious",
    pronunciation: "/ləˈɡuːbriəs/",
    partOfSpeech: "adjective",
    meaning: "Looking or sounding sad and dismal",
    hindiMeaning: "विषादपूर्ण; उदास",
    example: "The lugubrious music set a sombre tone for the evening.",
    synonyms: ["mournful", "gloomy", "melancholy"],
    antonyms: ["cheerful", "joyful", "happy"],
    frequency: 5,
    yearsAsked: [2024],
    category: "emotions",
    difficulty: "hard",
    root: "lugere (to mourn)"
  },
  {
    id: "w081",
    word: "nebulous",
    pronunciation: "/ˈnebjʊləs/",
    partOfSpeech: "adjective",
    meaning: "Unclear, vague, or ill-defined",
    hindiMeaning: "अस्पष्ट; धुंधला",
    example: "The plan remained nebulous with no clear implementation strategy.",
    synonyms: ["vague", "hazy", "indistinct"],
    antonyms: ["clear", "distinct", "precise"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "nebula (cloud/mist)"
  },
  {
    id: "w082",
    word: "obdurate",
    pronunciation: "/ˈɒbdjʊrət/",
    partOfSpeech: "adjective",
    meaning: "Stubbornly refusing to change one's opinion",
    hindiMeaning: "अडिग; हठी",
    example: "The obdurate negotiator refused to compromise on any point.",
    synonyms: ["stubborn", "inflexible", "unyielding"],
    antonyms: ["flexible", "amenable", "yielding"],
    frequency: 4,
    yearsAsked: [2023],
    category: "descriptions",
    difficulty: "hard",
    root: "ob- (against) + durare (to harden)"
  },
  {
    id: "w083",
    word: "pragmatic",
    pronunciation: "/præɡˈmætɪk/",
    partOfSpeech: "adjective",
    meaning: "Dealing with things sensibly and realistically",
    hindiMeaning: "व्यावहारिक; यथार्थवादी",
    example: "The government took a pragmatic approach to the economic crisis.",
    synonyms: ["practical", "realistic", "sensible"],
    antonyms: ["idealistic", "impractical", "theoretical"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "academic",
    difficulty: "medium",
    root: "pragma (deed/business)"
  },
  {
    id: "w084",
    word: "quixotic",
    pronunciation: "/kwɪkˈsɒtɪk/",
    partOfSpeech: "adjective",
    meaning: "Extremely idealistic; unrealistic and impractical",
    hindiMeaning: "अव्यावहारिक; स्वप्नलोक का",
    example: "His quixotic quest for a perfect society was doomed to fail.",
    synonyms: ["idealistic", "romantic", "impractical"],
    antonyms: ["practical", "realistic", "sensible"],
    frequency: 4,
    yearsAsked: [2023],
    category: "descriptions",
    difficulty: "hard",
    root: "Don Quixote (Cervantes' novel)"
  },
  {
    id: "w085",
    word: "rancorous",
    pronunciation: "/ˈræŋkərəs/",
    partOfSpeech: "adjective",
    meaning: "Showing deep-seated resentment or ill-will",
    hindiMeaning: "द्वेषपूर्ण; शत्रुतापूर्ण",
    example: "The rancorous debate damaged the reputation of both parties.",
    synonyms: ["bitter", "hostile", "resentful"],
    antonyms: ["friendly", "amiable", "benevolent"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "rancor (bitterness)"
  },
  {
    id: "w086",
    word: "supersede",
    pronunciation: "/ˌsuːpəˈsiːd/",
    partOfSpeech: "verb",
    meaning: "To take the place of; to replace",
    hindiMeaning: "स्थान लेना; प्रतिस्थापित करना",
    example: "The new policy will supersede the existing guidelines.",
    synonyms: ["replace", "supplant", "succeed"],
    antonyms: ["maintain", "retain", "preserve"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "actions",
    difficulty: "medium",
    root: "super (above) + cedere (to go)"
  },
  {
    id: "w087",
    word: "truculent",
    pronunciation: "/ˈtrʌkjʊlənt/",
    partOfSpeech: "adjective",
    meaning: "Eager or quick to argue or fight",
    hindiMeaning: "उग्र; आक्रामक",
    example: "His truculent attitude made negotiations impossible.",
    synonyms: ["aggressive", "belligerent", "combative"],
    antonyms: ["peaceful", "docile", "gentle"],
    frequency: 4,
    yearsAsked: [2023],
    category: "emotions",
    difficulty: "hard",
    root: "truculentus (fierce)"
  },
  {
    id: "w088",
    word: "umbrage",
    pronunciation: "/ˈʌmbrɪdʒ/",
    partOfSpeech: "noun",
    meaning: "Offence or annoyance",
    hindiMeaning: "आपत्ति; अपमान",
    example: "She took umbrage at his dismissive comments.",
    synonyms: ["offence", "resentment", "displeasure"],
    antonyms: ["pleasure", "delight", "approval"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "umbra (shadow/shade)"
  },
  {
    id: "w089",
    word: "vehement",
    pronunciation: "/ˈviːəmənt/",
    partOfSpeech: "adjective",
    meaning: "Showing strong feeling; forceful or passionate",
    hindiMeaning: "तीव्र; जोरदार",
    example: "The opposition made vehement protests against the new law.",
    synonyms: ["passionate", "fierce", "intense"],
    antonyms: ["mild", "gentle", "apathetic"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "vehemens (forceful)"
  },
  {
    id: "w090",
    word: "wanton",
    pronunciation: "/ˈwɒntən/",
    partOfSpeech: "adjective",
    meaning: "Deliberate and unprovoked; having no reason",
    hindiMeaning: "स्वच्छंद; निरंकुश",
    example: "The wanton destruction of public property was condemned.",
    synonyms: ["deliberate", "unprovoked", "arbitrary"],
    antonyms: ["restrained", "controlled", "deliberate"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "wan (lacking) + -ton"
  },
  {
    id: "w091",
    word: "afluent",
    pronunciation: "/ˈæfluənt/",
    partOfSpeech: "adjective",
    meaning: "Having a great deal of money; wealthy",
    hindiMeaning: "समृद्ध; धनी",
    example: "The affluent neighbourhood had the best schools.",
    synonyms: ["wealthy", "prosperous", "opulent"],
    antonyms: ["poor", "impoverished", "destitute"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "economy",
    difficulty: "medium",
    root: "ad- (to) + fluere (to flow)"
  },
  {
    id: "w092",
    word: "congenial",
    pronunciation: "/kənˈdʒiːniəl/",
    partOfSpeech: "adjective",
    meaning: "Pleasant because of shared interests; compatible",
    hindiMeaning: "सुसंगत; मिलनसार",
    example: "The congenial atmosphere at the office made work enjoyable.",
    synonyms: ["agreeable", "pleasant", "compatible"],
    antonyms: ["hostile", "unpleasant", "incompatible"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "social",
    difficulty: "medium",
    root: "con- (together) + genius (spirit)"
  },
  {
    id: "w093",
    word: "destitute",
    pronunciation: "/ˈdestɪtjuːt/",
    partOfSpeech: "adjective",
    meaning: "Without the basic necessities of life; very poor",
    hindiMeaning: "निर्धन; अभावग्रस्त",
    example: "The flood left thousands of families destitute.",
    synonyms: ["impoverished", "poor", "penniless"],
    antonyms: ["affluent", "wealthy", "prosperous"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "economy",
    difficulty: "medium",
    root: "destituere (to abandon)"
  },
  {
    id: "w094",
    word: "erudite",
    pronunciation: "/ˈerʊdaɪt/",
    partOfSpeech: "adjective",
    meaning: "Having or showing great knowledge or learning",
    hindiMeaning: "विद्वान; पंडित",
    example: "The erudite scholar published papers on ancient Indian texts.",
    synonyms: ["learned", "scholarly", "intellectual"],
    antonyms: ["ignorant", "uneducated", "illiterate"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "academic",
    difficulty: "medium",
    root: "erudire (to educate)"
  },
  {
    id: "w095",
    word: "fervent",
    pronunciation: "/ˈfɜːvənt/",
    partOfSpeech: "adjective",
    meaning: "Having or displaying passionate intensity",
    hindiMeaning: "उत्साही; तीव्र",
    example: "The reformer made a fervent appeal for social justice.",
    synonyms: ["passionate", "ardent", "zealous"],
    antonyms: ["apathetic", "indifferent", "lukewarm"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "fervere (to boil)"
  },
  {
    id: "w096",
    word: "garrulous",
    pronunciation: "/ˈɡærələs/",
    partOfSpeech: "adjective",
    meaning: "Excessively talkative, especially on trivial matters",
    hindiMeaning: "बातूनी; अधिक बोलने वाला",
    example: "The garrulous neighbour kept us talking for hours.",
    synonyms: ["talkative", "loquacious", "chatty"],
    antonyms: ["reticent", "taciturn", "quiet"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "social",
    difficulty: "medium",
    root: "garrulus (chattering)"
  },
  {
    id: "w097",
    word: "hegemony",
    pronunciation: "/hɪˈɡeməni/",
    partOfSpeech: "noun",
    meaning: "Leadership or dominance over others",
    hindiMeaning: "प्रभुत्व; नेतृत्व",
    example: "The nation sought economic hegemony in the region.",
    synonyms: ["dominance", "supremacy", "authority"],
    antonyms: ["subordination", "subservience"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "social",
    difficulty: "medium",
    root: "hegemon (leader)"
  },
  {
    id: "w098",
    word: "idiosyncratic",
    pronunciation: "/ˌɪdiəsɪŋˈkrætɪk/",
    partOfSpeech: "adjective",
    meaning: "Relating to distinctive individual characteristics",
    hindiMeaning: "विशिष्ट; व्यक्तिगत",
    example: "His idiosyncratic style of management confused his subordinates.",
    synonyms: ["distinctive", "peculiar", "individual"],
    antonyms: ["typical", "conventional", "standard"],
    frequency: 4,
    yearsAsked: [2023],
    category: "academic",
    difficulty: "hard",
    root: "idio (own) + synkrasis (mixture)"
  },
  {
    id: "w099",
    word: "jubilant",
    pronunciation: "/ˈdʒuːbɪlənt/",
    partOfSpeech: "adjective",
    meaning: "Feeling or expressing great happiness and triumph",
    hindiMeaning: "हर्षित; आनंदित",
    example: "The jubilant crowds celebrated the team's victory.",
    synonyms: ["elated", "triumphant", "ecstatic"],
    antonyms: ["miserable", "despondent", "gloomy"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "emotions",
    difficulty: "easy",
    root: "jubilare (to shout for joy)"
  },
  {
    id: "w100",
    word: "lethargic",
    pronunciation: "/ləˈθɑːdʒɪk/",
    partOfSpeech: "adjective",
    meaning: "Affected by a lack of energy; sluggish",
    hindiMeaning: "सुस्त; आलसी",
    example: "The lethargic economy showed no signs of recovery.",
    synonyms: ["sluggish", "drowsy", "torpid"],
    antonyms: ["energetic", "vigorous", "active"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "easy",
    root: "lethe (forgetfulness) + argos (idle)"
  },
  {
    id: "w101",
    word: "nostalgia",
    pronunciation: "/nɒˈstældʒə/",
    partOfSpeech: "noun",
    meaning: "A sentimental longing for the past",
    hindiMeaning: "पुरानी यादों की लालसा; विरह",
    example: "She felt a wave of nostalgia looking at old photographs.",
    synonyms: ["longing", "yearning", "wistfulness"],
    antonyms: ["anticipation", "indifference"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "emotions",
    difficulty: "easy",
    root: "nostos (return home) + algos (pain)"
  },
  {
    id: "w102",
    word: "ostensible",
    pronunciation: "/ɒˈstensɪbəl/",
    partOfSpeech: "adjective",
    meaning: "Stated or appearing to be true, but not necessarily so",
    hindiMeaning: "दिखावटी; प्रतीत होने वाला",
    example: "The ostensible reason for his visit was business, but he had other plans.",
    synonyms: ["apparent", "seeming", "supposed"],
    antonyms: ["real", "genuine", "actual"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "ostendere (to show)"
  },
  {
    id: "w103",
    word: "perennial",
    pronunciation: "/pəˈreniəl/",
    partOfSpeech: "adjective",
    meaning: "Lasting for an indefinite time; recurring",
    hindiMeaning: "सदाबहार; लगातार",
    example: "Poverty remains a perennial problem in developing nations.",
    synonyms: ["persistent", "enduring", "eternal"],
    antonyms: ["temporary", "fleeting", "transient"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "nature",
    difficulty: "medium",
    root: "per- (through) + annus (year)"
  },
  {
    id: "w104",
    word: "quiescent",
    pronunciation: "/kwiˈesənt/",
    partOfSpeech: "adjective",
    meaning: "In a state of inactivity or dormancy",
    hindiMeaning: "शांत; निष्क्रिय",
    example: "The volcano has been quiescent for several decades.",
    synonyms: ["dormant", "inactive", "latent"],
    antonyms: ["active", "restless", "vigorous"],
    frequency: 4,
    yearsAsked: [2023],
    category: "nature",
    difficulty: "hard",
    root: "quies (rest)"
  },
  {
    id: "w105",
    word: "recalcitrant",
    pronunciation: "/rɪˈkælsɪtrənt/",
    partOfSpeech: "adjective",
    meaning: "Having an obstinately uncooperative attitude",
    hindiMeaning: "अवज्ञाकारी; बागी",
    example: "The recalcitrant student refused to follow school rules.",
    synonyms: ["defiant", "unruly", "obstinate"],
    antonyms: ["obedient", "compliant", "cooperative"],
    frequency: 4,
    yearsAsked: [2023],
    category: "social",
    difficulty: "hard",
    root: "re- (back) + calcitrare (to kick)"
  },
  {
    id: "w106",
    word: "salubrious",
    pronunciation: "/səˈluːbriəs/",
    partOfSpeech: "adjective",
    meaning: "Health-giving; healthy",
    hindiMeaning: "स्वास्थ्यकर; सेहतमंद",
    example: "The salubrious climate of the hill station improved his health.",
    synonyms: ["healthy", "wholesome", "beneficial"],
    antonyms: ["unhealthy", "harmful", "noxious"],
    frequency: 4,
    yearsAsked: [2023],
    category: "nature",
    difficulty: "hard",
    root: "salus (health)"
  },
  {
    id: "w107",
    word: "trepidation",
    pronunciation: "/ˌtrepɪˈdeɪʃən/",
    partOfSpeech: "noun",
    meaning: "A feeling of fear or agitation about something",
    hindiMeaning: "भय; घबराहट",
    example: "She entered the exam hall with trepidation.",
    synonyms: ["fear", "anxiety", "apprehension"],
    antonyms: ["confidence", "calmness", "courage"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "trepidare (to tremble)"
  },
  {
    id: "w108",
    word: "vacillate",
    pronunciation: "/ˈvæsɪleɪt/",
    partOfSpeech: "verb",
    meaning: "To waver between different opinions; indecisive",
    hindiMeaning: "हिचकिचाना; अनिश्चित होना",
    example: "He continued to vacillate between the two job offers.",
    synonyms: ["waver", "falter", "hesitate"],
    antonyms: ["decide", "resolve", "determine"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "actions",
    difficulty: "medium",
    root: "vacillare (to sway)"
  },
  {
    id: "w109",
    word: "xenophobia",
    pronunciation: "/ˌzenəˈfəʊbiə/",
    partOfSpeech: "noun",
    meaning: "Dislike of or prejudice against people from other countries",
    hindiMeaning: "विदेशी भय; परदेशी विरोध",
    example: "Rising xenophobia has led to anti-immigrant legislation.",
    synonyms: ["racism", "intolerance", "bigotry"],
    antonyms: ["tolerance", "acceptance", "cosmopolitanism"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "social",
    difficulty: "medium",
    root: "xeno (foreign) + phobia (fear)"
  },
  {
    id: "w110",
    word: "yokel",
    pronunciation: "/ˈjəʊkəl/",
    partOfSpeech: "noun",
    meaning: "An unsophisticated country person",
    hindiMeaning: "देहाती; गंवार",
    example: "He was dismissed as a yokel by the city dwellers.",
    synonyms: ["rustic", "bumpkin", "hick"],
    antonyms: ["cosmopolitan", "sophisticated"],
    frequency: 5,
    yearsAsked: [2024],
    category: "social",
    difficulty: "hard",
    root: "English dialect yokel (simpleton)"
  },
  {
    id: "w111",
    word: "zenith",
    pronunciation: "/ˈzenɪθ/",
    partOfSpeech: "noun",
    meaning: "The time at which something is most powerful or successful",
    hindiMeaning: "चरम बिंदु; शिखर",
    example: "The Mughal Empire reached its zenith under Aurangzeb.",
    synonyms: ["peak", "apex", "summit"],
    antonyms: ["nadir", "trough", "bottom"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "nature",
    difficulty: "medium",
    root: "samt (Arabic: path overhead)"
  },
  {
    id: "w112",
    word: "acquiesce",
    pronunciation: "/ˌækwiˈes/",
    partOfSpeech: "verb",
    meaning: "To accept something reluctantly without protest",
    hindiMeaning: "सहमत होना; मान लेना",
    example: "She had to acquiesce to the demands of the management.",
    synonyms: ["consent", "comply", "yield"],
    antonyms: ["resist", "protest", "rebel"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "actions",
    difficulty: "medium",
    root: "acquiescere (to rest/remain)"
  },
  {
    id: "w113",
    word: "bolster",
    pronunciation: "/ˈbəʊlstə/",
    partOfSpeech: "verb",
    meaning: "To support or strengthen; prop up",
    hindiMeaning: "सहारा देना; मजबूत करना",
    example: "The new data bolstered the argument for policy reform.",
    synonyms: ["strengthen", "reinforce", "support"],
    antonyms: ["undermine", "weaken", "hinder"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "actions",
    difficulty: "medium",
    root: "bolster (cushion/support)"
  },
  {
    id: "w114",
    word: "cogent",
    pronunciation: "/ˈkəʊdʒənt/",
    partOfSpeech: "adjective",
    meaning: "Clear, logical, and convincing",
    hindiMeaning: "प्रभावशाली; सुसंगत",
    example: "She presented a cogent argument for education reform.",
    synonyms: ["convincing", "compelling", "persuasive"],
    antonyms: ["unconvincing", "weak", "feeble"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "academic",
    difficulty: "medium",
    root: "co- (together) + agere (to drive)"
  },
  {
    id: "w115",
    word: "disseminate",
    pronunciation: "/dɪˈsemɪneɪt/",
    partOfSpeech: "verb",
    meaning: "To spread information widely",
    hindiMeaning: "प्रसारित करना; फैलाना",
    example: "The organization works to disseminate knowledge about health.",
    synonyms: ["spread", "circulate", "distribute"],
    antonyms: ["suppress", "conceal", "withhold"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "actions",
    difficulty: "medium",
    root: "dis- (apart) + serere (to sow)"
  },
  {
    id: "w116",
    word: "equivocal",
    pronunciation: "/ɪˈkwɪvəkəl/",
    partOfSpeech: "adjective",
    meaning: "Open to more than one interpretation; ambiguous",
    hindiMeaning: "दोअर्थी; अस्पष्ट",
    example: "The minister gave an equivocal response to the question.",
    synonyms: ["ambiguous", "vague", "unclear"],
    antonyms: ["unequivocal", "clear", "definite"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "academic",
    difficulty: "medium",
    root: "aequus (equal) + vocis (voice)"
  },
  {
    id: "w117",
    word: "fluctuate",
    pronunciation: "/ˈflʌktʃueɪt/",
    partOfSpeech: "verb",
    meaning: "To rise and fall irregularly in number or amount",
    hindiMeaning: "उतार-चढ़ाव होना",
    example: "Prices continue to fluctuate due to market uncertainty.",
    synonyms: ["vary", "oscillate", "waver"],
    antonyms: ["stabilize", "remain constant"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "economy",
    difficulty: "medium",
    root: "fluctuare (to flow/wave)"
  },
  {
    id: "w118",
    word: "gratuitous",
    pronunciation: "/ɡrəˈtjuːɪtəs/",
    partOfSpeech: "adjective",
    meaning: "Uncalled for; lacking good reason; unwarranted",
    hindiMeaning: "बेवजह; अनावश्यक",
    example: "The movie contained gratuitous violence that added nothing to the plot.",
    synonyms: ["unwarranted", "unnecessary", "unjustified"],
    antonyms: ["necessary", "warranted", "justified"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "gratuitus (free/gratuitous)"
  },
  {
    id: "w119",
    word: "heresy",
    pronunciation: "/ˈherəsi/",
    partOfSpeech: "noun",
    meaning: "Belief or opinion contrary to established doctrine",
    hindiMeaning: "मतांतर; परंपरा विरुद्ध विचार",
    example: "His views on economic policy were considered heresy by the establishment.",
    synonyms: ["dissent", "blasphemy", "unorthodoxy"],
    antonyms: ["orthodoxy", "conformity", "dogma"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "legal",
    difficulty: "medium",
    root: "hairesis (choosing)"
  },
  {
    id: "w120",
    word: "inadvertent",
    pronunciation: "/ˌɪnədˈvɜːtənt/",
    partOfSpeech: "adjective",
    meaning: "Not resulting from or achieved through deliberate planning",
    hindiMeaning: "अनजाने में किया गया; अनिच्छापूर्वक",
    example: "The inadvertent error in the report caused confusion.",
    synonyms: ["unintentional", "accidental", "unplanned"],
    antonyms: ["deliberate", "intentional", "planned"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "in- (not) + advertere (to turn to)"
  },
  {
    id: "w121",
    word: "juxtapose",
    pronunciation: "/ˌdʒʌkstəˈpəʊz/",
    partOfSpeech: "verb",
    meaning: "To place side by side for comparison or contrast",
    hindiMeaning: "तुलना के लिए साथ रखना",
    example: "The exhibition juxtaposes ancient and modern art.",
    synonyms: ["compare", "contrast", "set beside"],
    antonyms: ["separate", "isolate", "distance"],
    frequency: 4,
    yearsAsked: [2023],
    category: "academic",
    difficulty: "hard",
    root: "juxta (near) + pos (to place)"
  },
  {
    id: "w122",
    word: "kinetic",
    pronunciation: "/kɪˈnetɪk/",
    partOfSpeech: "adjective",
    meaning: "Relating to or resulting from motion",
    hindiMeaning: "गतिशील; गति संबंधी",
    example: "The kinetic energy of the moving car was enormous.",
    synonyms: ["dynamic", "active", "moving"],
    antonyms: ["static", "stationary", "motionless"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "academic",
    difficulty: "medium",
    root: "kinesis (motion)"
  },
  {
    id: "w123",
    word: "labyrinthine",
    pronunciation: "/ˌlæbəˈrɪnθɪn/",
    partOfSpeech: "adjective",
    meaning: "Complicated and difficult to follow or understand",
    hindiMeaning: "भूलभुलैया जैसा; जटिल",
    example: "The labyrinthine bureaucracy made the process extremely slow.",
    synonyms: ["complex", "intricate", "convoluted"],
    antonyms: ["simple", "straightforward", "clear"],
    frequency: 4,
    yearsAsked: [2023],
    category: "descriptions",
    difficulty: "hard",
    root: "labyrinthos (maze)"
  },
  {
    id: "w124",
    word: "moratorium",
    pronunciation: "/ˌmɒrəˈtɔːriəm/",
    partOfSpeech: "noun",
    meaning: "A temporary prohibition of an activity",
    hindiMeaning: "स्थगन; अस्थायी रोक",
    example: "The government imposed a moratorium on new construction projects.",
    synonyms: ["ban", "suspension", "prohibition"],
    antonyms: ["permission", "approval", "continuation"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "legal",
    difficulty: "medium",
    root: "morari (to delay)"
  },
  {
    id: "w125",
    word: "negate",
    pronunciation: "/nɪˈɡeɪt/",
    partOfSpeech: "verb",
    meaning: "To make ineffective; nullify",
    hindiMeaning: "अमान्य करना; निरस्त करना",
    example: "His rude behaviour negated all the good work he had done.",
    synonyms: ["nullify", "invalidate", "counteract"],
    antonyms: ["confirm", "validate", "affirm"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "actions",
    difficulty: "medium",
    root: "negare (to deny)"
  },
  {
    id: "w126",
    word: "onset",
    pronunciation: "/ˈɒnset/",
    partOfSpeech: "noun",
    meaning: "The beginning or early stages of something",
    hindiMeaning: "आरंभ; शुरुआत",
    example: "The onset of monsoon brought relief from the heat.",
    synonyms: ["beginning", "start", "commencement"],
    antonyms: ["end", "conclusion", "finish"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "nature",
    difficulty: "easy",
    root: "on + set (to set upon)"
  },
  {
    id: "w127",
    word: "paragon",
    pronunciation: "/ˈpærəɡən/",
    partOfSpeech: "noun",
    meaning: "A model of excellence or perfection",
    hindiMeaning: "आदर्श; नमूना",
    example: "She is a paragon of honesty in public life.",
    synonyms: ["exemplar", "model", "epitome"],
    antonyms: ["failure", "antithesis"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "paragone (comparison)"
  },
  {
    id: "w128",
    word: "ramification",
    pronunciation: "/ˌræmɪfɪˈkeɪʃən/",
    partOfSpeech: "noun",
    meaning: "A consequence or effect of an action or decision",
    hindiMeaning: "परिणाम; दुष्प्रभाव",
    example: "The policy change had far-reaching ramifications for the economy.",
    synonyms: ["consequence", "effect", "outcome"],
    antonyms: ["cause", "origin", "source"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "academic",
    difficulty: "medium",
    root: "ramus (branch)"
  },
  {
    id: "w129",
    word: "substantiate",
    pronunciation: "/səbˈstænʃieɪt/",
    partOfSpeech: "verb",
    meaning: "To provide evidence to support or prove the truth of",
    hindiMeaning: "प्रमाणित करना; पुष्टि करना",
    example: "The researcher could not substantiate her claims with data.",
    synonyms: ["verify", "confirm", "validate"],
    antonyms: ["refute", "disprove", "contradict"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "legal",
    difficulty: "medium",
    root: "substantia (substance)"
  },
  {
    id: "w130",
    word: "tangential",
    pronunciation: "/tænˈdʒenʃəl/",
    partOfSpeech: "adjective",
    meaning: "Barely relevant to a matter; peripheral",
    hindiMeaning: "अप्रासंगिक; संबंधहीन",
    example: "His tangential remarks were not relevant to the main issue.",
    synonyms: ["peripheral", "marginal", "incidental"],
    antonyms: ["relevant", "pertinent", "central"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "academic",
    difficulty: "medium",
    root: "tangere (to touch)"
  },
  {
    id: "w131",
    word: "utilitarian",
    pronunciation: "/juːˌtɪlɪˈteəriən/",
    partOfSpeech: "adjective",
    meaning: "Designed to be useful rather than attractive",
    hindiMeaning: "उपयोगी; व्यावहारिक",
    example: "The government adopted a utilitarian approach to public spending.",
    synonyms: ["practical", "functional", "pragmatic"],
    antonyms: ["ornamental", "decorative", "aesthetic"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "academic",
    difficulty: "medium",
    root: "utilitas (usefulness)"
  },
  {
    id: "w132",
    word: "visceral",
    pronunciation: "/ˈvɪsərəl/",
    partOfSpeech: "adjective",
    meaning: "Relating to deep inward feelings rather than the mind",
    hindiMeaning: "अंतर्निहित; गहरा",
    example: "The audience had a visceral reaction to the powerful film.",
    synonyms: ["instinctive", "intuitive", "gut"],
    antonyms: ["rational", "intellectual", "calculated"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "emotions",
    difficulty: "medium",
    root: "viscera (internal organs)"
  },
  {
    id: "w133",
    word: "wane",
    pronunciation: "/weɪn/",
    partOfSpeech: "verb",
    meaning: "To decrease gradually in power, size, or extent",
    hindiMeaning: "क्षीण होना; घटना",
    example: "Public interest in the issue began to wane after a few weeks.",
    synonyms: ["diminish", "decline", "fade"],
    antonyms: ["wax", "grow", "increase"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "nature",
    difficulty: "easy",
    root: "wanian (to lessen)"
  },
  {
    id: "w134",
    word: "exacerbate",
    pronunciation: "/ɪɡˈzæsəbeɪt/",
    partOfSpeech: "verb",
    meaning: "To make a problem or situation worse",
    hindiMeaning: "बिगाड़ना; और खराब करना",
    example: "The drought was exacerbated by poor water management policies.",
    synonyms: ["worsen", "aggravate", "intensify"],
    antonyms: ["alleviate", "mitigate", "improve"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "actions",
    difficulty: "medium",
    root: "ex- (out) + acerbus (bitter)"
  },
  {
    id: "w135",
    word: "frugal",
    pronunciation: "/ˈfruːɡəl/",
    partOfSpeech: "adjective",
    meaning: "Sparing or economical with money or food",
    hindiMeaning: "मितव्ययी; कंजूस नहीं बल्कि संतोषी",
    example: "A frugal lifestyle helped her save for the future.",
    synonyms: ["thrifty", "economical", "prudent"],
    antonyms: ["extravagant", "lavish", "wasteful"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "economy",
    difficulty: "easy",
    root: "frugalis (thrifty)"
  },
  {
    id: "w136",
    word: "hegemony",
    pronunciation: "/hɪˈɡeməni/",
    partOfSpeech: "noun",
    meaning: "Leadership or dominance, especially by one country or group",
    hindiMeaning: "प्रभुत्व; वर्चस्व",
    example: "The country sought economic hegemony in the region.",
    synonyms: ["dominance", "supremacy", "authority"],
    antonyms: ["subordination", "subservience"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "social",
    difficulty: "medium",
    root: "hegemon (leader)"
  },
  {
    id: "w137",
    word: "ineffable",
    pronunciation: "/ɪˈnefəbəl/",
    partOfSpeech: "adjective",
    meaning: "Too great or extreme to be expressed in words",
    hindiMeaning: "अवर्णनीय; अकथनीय",
    example: "The beauty of the Himalayas is ineffable.",
    synonyms: ["indescribable", "inexpressible", "unspeakable"],
    antonyms: ["describable", "expressible", "ordinary"],
    frequency: 4,
    yearsAsked: [2023],
    category: "emotions",
    difficulty: "hard",
    root: "in- (not) + effabilis (speakable)"
  },
  {
    id: "w138",
    word: "jaundiced",
    pronunciation: "/ˈdʒɔːndɪst/",
    partOfSpeech: "adjective",
    meaning: "Affected by bitterness, resentment, or envy",
    hindiMeaning: "विषैला; ईर्ष्यालु",
    example: "His jaundiced view of the world prevented him from seeing opportunities.",
    synonyms: ["cynical", "bitter", "prejudiced"],
    antonyms: ["optimistic", "fair", "unbiased"],
    frequency: 4,
    yearsAsked: [2023],
    category: "emotions",
    difficulty: "hard",
    root: "galbinus (yellow)"
  },
  {
    id: "w139",
    word: "lucid",
    pronunciation: "/ˈluːsɪd/",
    partOfSpeech: "adjective",
    meaning: "Expressed clearly; easy to understand",
    hindiMeaning: "स्पष्ट; सुबोध",
    example: "The professor gave a lucid explanation of the complex theory.",
    synonyms: ["clear", "coherent", "intelligible"],
    antonyms: ["confused", "muddled", "obscure"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "easy",
    root: "lucere (to shine)"
  },
  {
    id: "w140",
    word: "malfeasance",
    pronunciation: "/mælˈfiːzəns/",
    partOfSpeech: "noun",
    meaning: "Wrongdoing, especially by a public official",
    hindiMeaning: "भ्रष्टाचार; अनुचित आचरण",
    example: "The politician was charged with malfeasance in office.",
    synonyms: ["misconduct", "wrongdoing", "corruption"],
    antonyms: ["integrity", "propriety"],
    frequency: 4,
    yearsAsked: [2023],
    category: "legal",
    difficulty: "hard",
    root: "mal- (bad) + feasance (doing)"
  },
  {
    id: "w141",
    word: "nuance",
    pronunciation: "/ˈnjuːɒns/",
    partOfSpeech: "noun",
    meaning: "A subtle difference in meaning or expression",
    hindiMeaning: "सूक्ष्म अंतर; प्रकांतर",
    example: "Understanding the nuances of the language takes years of practice.",
    synonyms: ["subtlety", "shade", "distinction"],
    antonyms: ["simplicity", "obviousness"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "academic",
    difficulty: "medium",
    root: "nuer (Latin: a cloud)"
  },
  {
    id: "w142",
    word: "opaque",
    pronunciation: "/əʊˈpeɪk/",
    partOfSpeech: "adjective",
    meaning: "Not able to be seen through; not transparent",
    hindiMeaning: "अपारदर्शी; स्पष्ट न होने वाला",
    example: "The company's opaque financial practices raised concerns.",
    synonyms: ["unclear", "obscure", "impenetrable"],
    antonyms: ["transparent", "clear", "lucid"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "opacus (shaded)"
  },
  {
    id: "w143",
    word: "propensity",
    pronunciation: "/prəˈpensɪti/",
    partOfSpeech: "noun",
    meaning: "An inclination or natural tendency to behave in a way",
    hindiMeaning: "प्रवृत्ति; झुकाव",
    example: "He has a propensity for taking risks in business.",
    synonyms: ["inclination", "tendency", "predisposition"],
    antonyms: ["reluctance", "aversion", "disinclination"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "pro- (forward) + pendere (to hang)"
  },
  {
    id: "w144",
    word: "resilience",
    pronunciation: "/rɪˈzɪliəns/",
    partOfSpeech: "noun",
    meaning: "The capacity to recover quickly from difficulties",
    hindiMeaning: "लचीलापन; सहनशक्ति",
    example: "The resilience of the Indian economy during the crisis was remarkable.",
    synonyms: ["toughness", "strength", "adaptability"],
    antonyms: ["fragility", "vulnerability"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "resilire (to jump back)"
  },
  {
    id: "w145",
    word: "spurious",
    pronunciation: "/ˈspjʊəriəs/",
    partOfSpeech: "adjective",
    meaning: "Not being what it purports to be; false or fake",
    hindiMeaning: "झूठा; कृत्रिम",
    example: "The spurious claims were dismissed by the court.",
    synonyms: ["false", "fake", "fraudulent"],
    antonyms: ["genuine", "authentic", "legitimate"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "legal",
    difficulty: "medium",
    root: "spurius (illegitimate)"
  },
  {
    id: "w146",
    word: "terse",
    pronunciation: "/tɜːs/",
    partOfSpeech: "adjective",
    meaning: "Sparing in the use of words; abrupt",
    hindiMeaning: "संक्षिप्त; छोटा",
    example: "His terse reply indicated he was not interested in further discussion.",
    synonyms: ["brief", "concise", "curt"],
    antonyms: ["verbose", "wordy", "long-winded"],
    frequency: 2,
    yearsAsked: [2021, 2023, 2024],
    category: "descriptions",
    difficulty: "medium",
    root: "tersus (wiped off)"
  },
  {
    id: "w147",
    word: "vindicate",
    pronunciation: "/ˈvɪndɪkeɪt/",
    partOfSpeech: "verb",
    meaning: "To clear someone of blame or suspicion",
    hindiMeaning: "निर्दोष सिद्ध करना; सफाई देना",
    example: "The court ruling vindicated the whistleblower's actions.",
    synonyms: ["exonerate", "justify", "absolve"],
    antonyms: ["blame", "condemn", "accuse"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "legal",
    difficulty: "medium",
    root: "vindicare (to claim)"
  },
  {
    id: "w148",
    word: "wily",
    pronunciation: "/ˈwaɪli/",
    partOfSpeech: "adjective",
    meaning: "Having or showing a sly and cunning mind",
    hindiMeaning: "चालाक; धूर्त",
    example: "The wily politician outmaneuvered all his opponents.",
    synonyms: ["cunning", "crafty", "sly"],
    antonyms: ["naive", "innocent", "straightforward"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "social",
    difficulty: "medium",
    root: "wile (cunning device)"
  },
  {
    id: "w149",
    word: "yoke",
    pronunciation: "/jəʊk/",
    partOfSpeech: "noun",
    meaning: "A wooden crosspiece used to join two oxen; a bond or tie",
    hindiMeaning: "जुआ; बंधन",
    example: "The farmers broke free from the yoke of oppression.",
    synonyms: ["bond", "chain", "shackle"],
    antonyms: ["freedom", "liberty", "emancipation"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "nature",
    difficulty: "medium",
    root: "geoc (Old English: yoke)"
  },
  {
    id: "w150",
    word: "zealot",
    pronunciation: "/ˈzelət/",
    partOfSpeech: "noun",
    meaning: "A person who is fanatical about a cause",
    hindiMeaning: "कट्टरपंथी; उत्साही",
    example: "The zealot refused to listen to any opposing viewpoint.",
    synonyms: ["fanatic", "extremist", "activist"],
    antonyms: ["moderate", "pragmatist"],
    frequency: 3,
    yearsAsked: [2022, 2024],
    category: "social",
    difficulty: "medium",
    root: "zelos (zeal)"
  }
];